# Generated by Django 2.2.1 on 2019-06-18 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultPublicParam',
            fields=[
                ('name', models.CharField(default='', max_length=255, verbose_name='名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('channel_id', models.IntegerField(null=True, verbose_name='channel_id')),
                ('product_code', models.CharField(max_length=50, verbose_name='一级产品code')),
                ('sub_product_code', models.CharField(max_length=50, verbose_name='二级产品code')),
                ('market_channel_code', models.CharField(max_length=50, verbose_name='渠道code')),
                ('publice_params', models.TextField(blank=True, null=True, verbose_name='公共参数')),
            ],
            options={
                'db_table': 'default_public_param',
                'ordering': ['updated_time'],
            },
        ),
        migrations.CreateModel(
            name='RequestConfig',
            fields=[
                ('name', models.CharField(default='', max_length=255, verbose_name='名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_method', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=50, verbose_name='请求方式')),
                ('request_url', models.TextField(blank=True, null=True, verbose_name='接口地址')),
                ('request_header', models.TextField(blank=True, null=True, verbose_name='请求头文件')),
                ('path_param_template', models.TextField(blank=True, null=True, verbose_name='url中的参数')),
                ('query_param_template', models.TextField(blank=True, null=True, verbose_name='问号后的参数')),
                ('form_param_template', models.TextField(blank=True, null=True, verbose_name='表单格式的参数')),
                ('body_param_template', models.TextField(blank=True, null=True, verbose_name='raw格式的参数')),
                ('file_param_template', models.TextField(blank=True, null=True, verbose_name='文件格式的参数')),
            ],
            options={
                'db_table': 'request_config',
                'ordering': ['updated_time'],
            },
        ),
        migrations.CreateModel(
            name='RequestGroup',
            fields=[
                ('name', models.CharField(default='', max_length=255, verbose_name='名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'request_group',
                'ordering': ['updated_time'],
            },
        ),
        migrations.CreateModel(
            name='ResultGroup',
            fields=[
                ('name', models.CharField(default='', max_length=255, verbose_name='名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'result_group',
                'ordering': ['updated_time'],
            },
        ),
        migrations.CreateModel(
            name='ResultRelation',
            fields=[
                ('name', models.CharField(default='', max_length=255, verbose_name='名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createData.RequestConfig')),
                ('result_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createData.ResultGroup', verbose_name='组')),
            ],
            options={
                'db_table': 'result_relation',
                'ordering': ['updated_time'],
            },
        ),
        migrations.AddField(
            model_name='resultgroup',
            name='ResultGroup',
            field=models.ManyToManyField(through='createData.ResultRelation', to='createData.RequestConfig', verbose_name='每组api结果列表'),
        ),
        migrations.CreateModel(
            name='ResponseConfig',
            fields=[
                ('name', models.CharField(default='', max_length=255, verbose_name='名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dependent_param_list', models.TextField(blank=True, null=True, verbose_name='接口返回值里保存全局参数')),
                ('expect_response', models.TextField(blank=True, null=True, verbose_name='期待结果')),
                ('related_reqid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createData.RequestConfig', verbose_name='期待返回值对应的请求id')),
            ],
            options={
                'db_table': 'response_config',
                'ordering': ['updated_time'],
            },
        ),
        migrations.CreateModel(
            name='RequestRelation',
            fields=[
                ('name', models.CharField(default='', max_length=255, verbose_name='名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createData.RequestGroup')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createData.RequestConfig')),
            ],
            options={
                'db_table': 'request_relation',
                'ordering': ['updated_time'],
            },
        ),
        migrations.AddField(
            model_name='requestgroup',
            name='RequestGroup',
            field=models.ManyToManyField(through='createData.RequestRelation', to='createData.RequestConfig', verbose_name='请求id列表'),
        ),
        migrations.CreateModel(
            name='AutomationTestResult',
            fields=[
                ('name', models.CharField(default='', max_length=255, verbose_name='名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_method', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=50, verbose_name='请求方式')),
                ('request_url', models.TextField(blank=True, null=True, verbose_name='接口地址')),
                ('request_header', models.TextField(blank=True, null=True, verbose_name='请求头文件')),
                ('path_param_template', models.TextField(blank=True, null=True, verbose_name='url中的参数')),
                ('query_param_template', models.TextField(blank=True, null=True, verbose_name='问号后的参数')),
                ('form_param_template', models.TextField(blank=True, null=True, verbose_name='表单格式的参数')),
                ('body_param_template', models.TextField(blank=True, null=True, verbose_name='raw格式的参数')),
                ('file_param_template', models.TextField(blank=True, null=True, verbose_name='文件格式的参数')),
                ('statusCode', models.CharField(blank=True, choices=[('200', '200'), ('404', '404'), ('400', '400'), ('502', '502'), ('500', '500'), ('302', '302')], max_length=1024, null=True, verbose_name='期望HTTP状态')),
                ('result', models.CharField(choices=[('PASS', '成功'), ('FAIL', '失败')], max_length=50, verbose_name='测试结果')),
                ('responseData', models.TextField(blank=True, null=True, verbose_name='实际返回内容')),
                ('automationCaseApi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='createData.RequestConfig', verbose_name='接口')),
            ],
            options={
                'db_table': 'automation_test_result',
                'ordering': ['updated_time'],
            },
        ),
    ]
