# Generated by Django 2.2.1 on 2019-06-20 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationReportSendConfig',
            fields=[
                ('name', models.CharField(default='', max_length=255, verbose_name='名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reportFrom', models.EmailField(blank=True, max_length=1024, null=True, verbose_name='发送人邮箱')),
                ('mailUser', models.CharField(blank=True, max_length=1024, null=True, verbose_name='用户名')),
                ('mailPass', models.CharField(blank=True, max_length=1024, null=True, verbose_name='口令')),
                ('mailSmtp', models.CharField(blank=True, max_length=1024, null=True, verbose_name='邮箱服务器')),
                ('projectResultGroup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='createData.ResultGroup', verbose_name='项目')),
            ],
            options={
                'verbose_name': '邮件发送配置',
                'verbose_name_plural': '邮件发送配置',
            },
        ),
    ]
